#!/usr/bin/env tclsh
#
# A simple noweave, based on noweb, that allows us to do simple literate
# programming in Tcl.
#

namespace eval ::dac {
    variable chunks
    variable requestedChunk
    variable weave 0
    variable tangle 0
    variable argv0
    variable argv

    # Open a file with cleanup
    proc with-open-file {fname mode fp block} {
      upvar 1 $fp fpvar
      set binarymode 0
      if {[string equal [string index $mode end] b]} {
        set mode [string range $mode 0 end-1]
        set binarymode 1
      }
      set fpvar [open $fname $mode]
      if {$binarymode} {
        fconfigure $fpvar -translation binary
      }
      uplevel 1 $block
      close $fpvar
    }

    # Add or append to an associative array (multi-line chunks)
    proc add-array-value { _arr key value } {
      upvar 1 $_arr arr
      if {[info exists arr($key)]} {
        append arr($key) "\n$value"
      } else {
        array set arr [list $key $value]
      }
    }

    # Recursively expand referenced chunks
    proc expand-chunks {_arr chunk indent {parent ""}} {
      upvar 1 $_arr arr
      if {![info exists arr($chunk)]} {
        puts stderr "Error: Could not find chunk '$chunk'"
        if {$parent ne ""} {
            puts stderr "  referenced from chunk '$parent'"
        }
        puts stderr "Available chunks:"
        foreach key [lsort [array names arr]] {
          puts stderr "  $key"
        }
        exit 1
      }
      foreach line [split $arr($chunk) "\n"] {
        if {[regexp {^(\s*)(<<)(.*)(>>)\s*$} $line -> newIndent open newChunk close]} {
          expand-chunks arr $newChunk $newIndent $chunk
        } else {
          puts -nonewline "$indent"
          puts "$line"
        }
      }
    }

    # Print usage message
    proc Usage {} {
      variable argv0
      puts stderr "$argv0 \[-R <chunk_name>\) \[-t\] \[-w\] filename"
      exit 1
    }

    proc main {} {
        variable chunks
        variable requestedChunk
        variable weave
        variable tangle
        variable argv
        variable argv0

        # --- Initialize State ---
        array set chunks {}
        unset -nocomplain requestedChunk
        set weave 0
        set tangle 0

        # --- Parse Arguments ---
        while {[llength $argv]} {
          set argv [lassign $argv[set argv {}] flag]
          switch -glob $flag {
            -R {
              set argv [lassign $argv[set argv {}] requestedChunk]
            }
            -t {
              set tangle 1
            }
            -w {
              set weave 1
            }
            -h - --help - -\? {
              Usage
            }
            -- break
            -*
            {
              puts stderr "unknown option $flag"
              Usage
            }
            default {
              set argv [list $flag {*}$argv]
              break
            }
          }
        }

        if {$tangle && $weave} {
          puts stderr "Cannot use both tangle and weave options at the same time"
          Usage
        }

        if {!$tangle && !$weave} {
          set weave 1
        }

        # --- Check for filename ---
        if {[llength $argv] != 1} {
          puts stderr "No file given, exiting"
          Usage
        }
        set filename [lindex $argv 0]

        # Default to root chunk if none specified
        if {![info exists requestedChunk]} {
          set requestedChunk "*"
        }

        # --- Read and extract chunks from file ---
        with-open-file $filename r fp {
          set in_chunk_p 0
          unset -nocomplain chunk
          while 1 {
            gets $fp line
            if [eof $fp] break
            if {!$in_chunk_p && [regexp {(^<<)(.*)(>>=$)} $line -> open chunk close]} {
              set in_chunk_p 1
              continue
            }
            if {$in_chunk_p && [regexp {^\s*@\s*$} $line ]} {
              set in_chunk_p 0
              unset -nocomplain chunk
              continue
            }
            if {$in_chunk_p} {
              add-array-value chunks $chunk $line
            }
          }
        }

        # --- Output as requested ---
        if {$tangle} {
          expand-chunks chunks $requestedChunk ""
        }

        if {$weave} {
          with-open-file $filename r fp {
            set in_chunk_p 0
            unset -nocomplain chunk
            while 1 {
              gets $fp line
              if [eof $fp] break
              if {!$in_chunk_p && [regexp {(^<<)(.*)(>>=$)} $line -> open chunk close]} {
                set in_chunk_p 1
                expand-chunks chunks $chunk ""
                continue
              } elseif {$in_chunk_p && [regexp {\s*@\s*$} $line]} {
                set in_chunk_p 0
                unset -nocomplain chunk
                continue
              } elseif {$in_chunk_p} {
                # skip chunk lines during weave
              } else {
                puts "$line"
              }
            }
          }
        }

        exit 0
    }
}

set ::dac::argv0 $argv0
set ::dac::argv $argv
::dac::main

